namespace Centaur.Compositor {

    /**
     * labwc, the reference target.
     *
     * labwc has no IPC socket, so this backend is configuration-only: it owns
     * ~/.config/labwc/rc.xml and menu.xml and asks labwc to reread them.
     *
     * labwc draws its own titlebars, menus and window switcher, which GTK's
     * stylesheet never reaches. rc.xml therefore also selects the Centaur
     * labwc theme generated from the design tokens for the current palette
     * and accent (Centaur-<accent>-<palette>), and sets the interface font.
     *
     * KNOWN GAP -- workspaces and focus tracking report false. Reading them
     * needs the ext-workspace-v1 and wlr-foreign-toplevel-management Wayland
     * protocols, which means wayland-scanner and hand-written C: the one case
     * architecture.md section 2 admits C for. Until that exists the topbar
     * hides those two indicators rather than showing something wrong, which is
     * the Capabilities mechanism doing its job. A sway session has both today.
     */
    public class LabwcBackend : Object, Backend {

        private const string MARKER = "Generated by Centaur DE";

        public string name { owned get { return "labwc"; } }

        public Capabilities capabilities {
            get {
                return Capabilities () {
                    workspaces = false,
                    focus_tracking = false,
                    window_placement = true,
                    titlebar_buttons = true,
                    animation_duration = false,  // labwc animates nothing yet
                };
            }
        }

        public async void start () throws GLib.Error {
            // Nothing to connect to. Configuration is applied on demand.
        }

        public Workspace[] list_workspaces () {
            return {};
        }

        public Toplevel? focused_toplevel () {
            return null;
        }

        public async void switch_workspace (string id) throws GLib.Error {
            throw new Core.SystemError.NOT_SUPPORTED (
                "labwc exposes no workspace control to Centaur yet");
        }

        public async void apply_configuration () throws GLib.Error {
            var config = Core.Config.get_default ();

            yield write_owned (config_path ("rc.xml"), render (config));
            yield write_owned (config_path ("menu.xml"), render_menu ());

            reconfigure ();
        }

        private async void write_owned (string path, string contents) throws GLib.Error {
            preserve_existing (path);

            var file = File.new_for_path (path);
            var parent = file.get_parent ();
            if (parent != null && !parent.query_exists ()) {
                parent.make_directory_with_parents ();
            }

            yield file.replace_contents_async (
                contents.data, null, false, FileCreateFlags.NONE, null, null);
        }

        /**
         * Centaur owns rc.xml, so anything the user wrote by hand is copied
         * aside once before the first overwrite. Losing someone's compositor
         * configuration silently would be unforgivable; losing it loudly is
         * merely bad.
         */
        private void preserve_existing (string path) {
            if (!FileUtils.test (path, FileTest.EXISTS)) {
                return;
            }

            string contents;
            try {
                FileUtils.get_contents (path, out contents);
            } catch (FileError e) {
                Core.Log.warn ("cannot read %s: %s", path, e.message);
                return;
            }

            if (MARKER in contents) {
                return;  // already ours
            }

            var backup = path + ".pre-centaur";
            if (FileUtils.test (backup, FileTest.EXISTS)) {
                return;  // never overwrite the first backup
            }

            try {
                FileUtils.set_contents (backup, contents);
                Core.Log.warn ("existing labwc configuration saved to %s", backup);
            } catch (FileError e) {
                Core.Log.error ("cannot back up %s: %s", path, e.message);
            }
        }

        private string render (Core.Config config) {
            var settings = config.compositor;
            var placement = settings.get_string ("window-placement");
            var duration = settings.get_int ("animation-duration");
            var side = settings.get_string ("titlebar-side");
            var buttons = settings.get_strv ("titlebar-buttons");

            var theme = theme_name (config);
            string family;
            int size;
            parse_font (config.appearance.get_string ("font-ui"), out family, out size);

            var builder = new StringBuilder ();
            builder.append ("<?xml version=\"1.0\"?>\n");
            builder.append (@"<!-- $MARKER. Edits here are overwritten.\n");
            builder.append ("     Change these settings with gsettings, under org.centaur.compositor. -->\n");
            builder.append ("<labwc_config>\n");

            builder.append ("  <placement>\n");
            builder.append (@"    <policy>$(labwc_placement (placement))</policy>\n");
            builder.append ("  </placement>\n");

            builder.append ("  <theme>\n");
            if (theme != null) {
                builder.append (@"    <name>$theme</name>\n");
            }
            builder.append (@"    <titlebar>\n");
            builder.append (@"      <layout>$(labwc_titlebar (side, buttons))</layout>\n");
            builder.append ("    </titlebar>\n");
            // radius.md, like Centaur's own windows and popovers.
            builder.append ("    <cornerRadius>10</cornerRadius>\n");
            builder.append ("    <dropShadows>yes</dropShadows>\n");
            foreach (var place in new string[] {
                    "ActiveWindow", "InactiveWindow", "MenuHeader", "MenuItem", "OnScreenDisplay" }) {
                // Titles are semibold in Centaur's headerbars; labwc has bold.
                var weight = place.has_suffix ("Window") ? "bold" : "normal";
                builder.append (@"    <font place=\"$place\">\n");
                builder.append (@"      <name>$(Markup.escape_text (family))</name>\n");
                builder.append (@"      <size>$size</size>\n");
                builder.append (@"      <weight>$weight</weight>\n");
                builder.append ("    </font>\n");
            }
            builder.append ("  </theme>\n");

            // Text-only menus: labwc draws menu icons in their own colours, so
            // the symbolic icons the rest of Centaur uses would be near-black
            // on a dark menu.
            builder.append ("  <menu>\n");
            builder.append ("    <showIcons>no</showIcons>\n");
            builder.append ("  </menu>\n");

            // Screenshot keys. <default /> first: once rc.xml binds any key,
            // labwc drops all of its built-in bindings -- Alt+Tab included --
            // unless asked to keep them.
            builder.append ("  <keyboard>\n");
            builder.append ("    <default />\n");
            append_keybind (builder, "Print", "centaur-screenshot --screen");
            append_keybind (builder, "S-Print", "centaur-screenshot --area");
            append_keybind (builder, "W-S-s", "centaur-screenshot");
            builder.append ("  </keyboard>\n");

            // Recorded even though labwc ignores it, so the value survives a
            // move to a compositor that does animate.
            builder.append (@"  <!-- centaur:animation-duration $duration -->\n");

            builder.append ("</labwc_config>\n");
            return builder.str;
        }

        /**
         * The generated theme for the current palette and accent, or null when
         * it is not installed -- labwc then keeps its built-in look rather
         * than failing to load a theme that is not there.
         */
        private static string? theme_name (Core.Config config) {
            var palette = config.resolved_palette ();
            var accent = config.appearance.get_string ("accent");
            foreach (var candidate in new string[] {
                    @"Centaur-$accent-$palette", @"Centaur-emerald-$palette" }) {
                if (find_data (Path.build_filename ("themes", candidate, "labwc", "themerc")) != null) {
                    return candidate;
                }
            }
            Core.Log.warn ("no Centaur labwc theme installed; labwc keeps its own look");
            return null;
        }

        /** A file under the XDG data directories, user first. */
        private static string? find_data (string relative) {
            string[] dirs = { Environment.get_user_data_dir () };
            foreach (var dir in Environment.get_system_data_dirs ()) {
                dirs += dir;
            }
            foreach (var dir in dirs) {
                var path = Path.build_filename (dir, relative);
                if (FileUtils.test (path, FileTest.EXISTS)) {
                    return path;
                }
            }
            return null;
        }

        /** "Inter 10" or "Noto Sans Bold 11" -> family and point size. */
        private static void parse_font (string description, out string family, out int size) {
            family = "Inter";
            size = 10;
            var parts = description.strip ().split (" ");
            if (parts.length == 0 || parts[0] == "") {
                return;
            }
            var last = parts[parts.length - 1];
            int parsed = 0;
            if (parts.length > 1 && int.try_parse (last, out parsed) && parsed > 0) {
                size = parsed;
                parts = parts[0:parts.length - 1];
            }
            family = string.joinv (" ", parts);
        }

        /**
         * The desktop's right-click menu and every window's menu.
         *
         * The root menu leads to the things a desktop right-click is for:
         * a terminal, the wallpaper and the displays. Lock uses Centaur's
         * lock screen unless the user has their own swaylock configuration,
         * the same rule the topbar's power menu follows.
         */
        private static string render_menu () {
            var terminal = Environment.find_program_in_path ("lab-sensible-terminal") != null
                ? "lab-sensible-terminal"
                : null;

            var builder = new StringBuilder ();
            builder.append ("<?xml version=\"1.0\"?>\n");
            builder.append (@"<!-- $MARKER. Edits here are overwritten. -->\n");
            builder.append ("<openbox_menu>\n");

            builder.append ("  <menu id=\"root-menu\">\n");
            if (terminal != null) {
                append_item (builder, "Terminal", "Execute", terminal);
                builder.append ("    <separator />\n");
            }
            append_item (builder, "Take Screenshot…", "Execute", "centaur-screenshot");
            builder.append ("    <separator />\n");
            append_item (builder, "Change Background…", "Execute", "centaur-background");
            append_item (builder, "Display Settings…", "Execute", "centaur-displays");
            builder.append ("    <separator />\n");
            append_item (builder, "Lock Screen", "Execute", lock_command ());
            append_item (builder, "Log Out", "Exit", null);
            builder.append ("  </menu>\n");

            builder.append ("  <menu id=\"client-menu\">\n");
            append_item (builder, "Minimize", "Iconify", null);
            append_item (builder, "Maximize", "ToggleMaximize", null);
            append_item (builder, "Fullscreen", "ToggleFullscreen", null);
            append_item (builder, "Always on Top", "ToggleAlwaysOnTop", null);
            builder.append ("    <menu id=\"client-send-to-menu\" />\n");
            builder.append ("    <separator />\n");
            append_item (builder, "Close", "Close", null);
            builder.append ("  </menu>\n");

            builder.append ("</openbox_menu>\n");
            return builder.str;
        }

        private static void append_keybind (StringBuilder builder, string key, string command) {
            builder.append (@"    <keybind key=\"$key\">\n");
            builder.append (@"      <action name=\"Execute\" command=\"$(Markup.escape_text (command))\" />\n");
            builder.append ("    </keybind>\n");
        }

        private static void append_item (StringBuilder builder, string label,
                                         string action, string? command) {
            builder.append (@"    <item label=\"$(Markup.escape_text (label))\">\n");
            if (command != null) {
                builder.append (@"      <action name=\"$action\" command=\"$(Markup.escape_text (command))\" />\n");
            } else {
                builder.append (@"      <action name=\"$action\" />\n");
            }
            builder.append ("    </item>\n");
        }

        private static string lock_command () {
            var home = Environment.get_home_dir ();
            var personal = FileUtils.test (
                    Path.build_filename (Environment.get_user_config_dir (), "swaylock", "config"),
                    FileTest.EXISTS)
                || FileUtils.test (Path.build_filename (home, ".swaylock", "config"), FileTest.EXISTS);
            var ours = find_data (Path.build_filename ("centaur", "themes", "swaylock.conf"));
            if (personal || ours == null) {
                return "swaylock --daemonize";
            }
            return @"swaylock --daemonize --config $ours";
        }

        private static string labwc_placement (string value) {
            switch (value) {
                case "center":  return "center";
                case "cascade": return "cascade";
                case "cursor":  return "cursor";
                default:        return "automatic";
            }
        }

        /**
         * labwc writes the layout as a colon-separated pair: what sits left of
         * the title, then what sits right of it.
         */
        private static string labwc_titlebar (string side, string[] buttons) {
            var names = new StringBuilder ();
            foreach (var button in buttons) {
                if (names.len > 0) {
                    names.append (",");
                }
                switch (button) {
                    case "minimise": names.append ("iconify"); break;
                    case "maximise": names.append ("max"); break;
                    case "close":    names.append ("close"); break;
                    case "menu":     names.append ("menu"); break;
                    default: break;
                }
            }

            return (side == "left") ? @"$(names.str):" : @":$(names.str)";
        }

        private static void reconfigure () {
            try {
                string[] argv = { "labwc", "--reconfigure" };
                Process.spawn_async (null, argv, null,
                                     SpawnFlags.SEARCH_PATH | SpawnFlags.STDOUT_TO_DEV_NULL
                                     | SpawnFlags.STDERR_TO_DEV_NULL,
                                     null, null);
            } catch (SpawnError e) {
                Core.Log.warn ("cannot ask labwc to reconfigure: %s", e.message);
            }
        }

        private static string config_path (string name) {
            return Path.build_filename (
                Environment.get_user_config_dir (), "labwc", name);
        }
    }
}
