namespace Centaur.Compositor {

    /**
     * labwc, the reference target.
     *
     * labwc has no IPC socket, so this backend is configuration-only: it owns
     * ~/.config/labwc/rc.xml and asks labwc to reread it.
     *
     * KNOWN GAP -- workspaces and focus tracking report false. Reading them
     * needs the ext-workspace-v1 and wlr-foreign-toplevel-management Wayland
     * protocols, which means wayland-scanner and hand-written C: the one case
     * architecture.md section 2 admits C for. Until that exists the topbar
     * hides those two indicators rather than showing something wrong, which is
     * the Capabilities mechanism doing its job. A sway session has both today.
     */
    public class LabwcBackend : Object, Backend {

        private const string MARKER = "Generated by Centaur DE";

        public string name { owned get { return "labwc"; } }

        public Capabilities capabilities {
            get {
                return Capabilities () {
                    workspaces = false,
                    focus_tracking = false,
                    window_placement = true,
                    titlebar_buttons = true,
                    animation_duration = false,  // labwc animates nothing yet
                };
            }
        }

        public async void start () throws GLib.Error {
            // Nothing to connect to. Configuration is applied on demand.
        }

        public Workspace[] list_workspaces () {
            return {};
        }

        public Toplevel? focused_toplevel () {
            return null;
        }

        public async void switch_workspace (string id) throws GLib.Error {
            throw new Core.SystemError.NOT_SUPPORTED (
                "labwc exposes no workspace control to Centaur yet");
        }

        public async void apply_configuration () throws GLib.Error {
            var config = Core.Config.get_default ();
            var path = rc_path ();

            preserve_existing (path);

            var contents = render (config.compositor);
            var file = File.new_for_path (path);

            var parent = file.get_parent ();
            if (parent != null && !parent.query_exists ()) {
                parent.make_directory_with_parents ();
            }

            yield file.replace_contents_async (
                contents.data, null, false, FileCreateFlags.NONE, null, null);

            reconfigure ();
        }

        /**
         * Centaur owns rc.xml, so anything the user wrote by hand is copied
         * aside once before the first overwrite. Losing someone's compositor
         * configuration silently would be unforgivable; losing it loudly is
         * merely bad.
         */
        private void preserve_existing (string path) {
            if (!FileUtils.test (path, FileTest.EXISTS)) {
                return;
            }

            string contents;
            try {
                FileUtils.get_contents (path, out contents);
            } catch (FileError e) {
                Core.Log.warn ("cannot read %s: %s", path, e.message);
                return;
            }

            if (MARKER in contents) {
                return;  // already ours
            }

            var backup = path + ".pre-centaur";
            if (FileUtils.test (backup, FileTest.EXISTS)) {
                return;  // never overwrite the first backup
            }

            try {
                FileUtils.set_contents (backup, contents);
                Core.Log.warn ("existing labwc configuration saved to %s", backup);
            } catch (FileError e) {
                Core.Log.error ("cannot back up %s: %s", path, e.message);
            }
        }

        private string render (Settings settings) {
            var placement = settings.get_string ("window-placement");
            var duration = settings.get_int ("animation-duration");
            var side = settings.get_string ("titlebar-side");
            var buttons = settings.get_strv ("titlebar-buttons");

            var builder = new StringBuilder ();
            builder.append ("<?xml version=\"1.0\"?>\n");
            builder.append (@"<!-- $MARKER. Edits here are overwritten.\n");
            builder.append ("     Change these settings in Base Center > Appearance. -->\n");
            builder.append ("<labwc_config>\n");

            builder.append ("  <placement>\n");
            builder.append (@"    <policy>$(labwc_placement (placement))</policy>\n");
            builder.append ("  </placement>\n");

            builder.append ("  <theme>\n");
            builder.append (@"    <titlebar>\n");
            builder.append (@"      <layout>$(labwc_titlebar (side, buttons))</layout>\n");
            builder.append ("    </titlebar>\n");
            builder.append ("  </theme>\n");

            // Recorded even though labwc ignores it, so the value survives a
            // move to a compositor that does animate.
            builder.append (@"  <!-- centaur:animation-duration $duration -->\n");

            builder.append ("</labwc_config>\n");
            return builder.str;
        }

        private static string labwc_placement (string value) {
            switch (value) {
                case "center":  return "center";
                case "cascade": return "cascade";
                case "cursor":  return "cursor";
                default:        return "automatic";
            }
        }

        /**
         * labwc writes the layout as a colon-separated pair: what sits left of
         * the title, then what sits right of it.
         */
        private static string labwc_titlebar (string side, string[] buttons) {
            var names = new StringBuilder ();
            foreach (var button in buttons) {
                if (names.len > 0) {
                    names.append (",");
                }
                switch (button) {
                    case "minimise": names.append ("iconify"); break;
                    case "maximise": names.append ("max"); break;
                    case "close":    names.append ("close"); break;
                    case "menu":     names.append ("menu"); break;
                    default: break;
                }
            }

            return (side == "left") ? @"$(names.str):" : @":$(names.str)";
        }

        private static void reconfigure () {
            try {
                string[] argv = { "labwc", "--reconfigure" };
                Process.spawn_async (null, argv, null,
                                     SpawnFlags.SEARCH_PATH | SpawnFlags.STDOUT_TO_DEV_NULL
                                     | SpawnFlags.STDERR_TO_DEV_NULL,
                                     null, null);
            } catch (SpawnError e) {
                Core.Log.warn ("cannot ask labwc to reconfigure: %s", e.message);
            }
        }

        private static string rc_path () {
            return Path.build_filename (
                Environment.get_user_config_dir (), "labwc", "rc.xml");
        }
    }
}
