namespace Centaur.Settingsd {

    /**
     * Translates configuration outward.
     *
     * centaur-settingsd is not a store -- GSettings is. This watches keys and
     * applies them to things that cannot read GSettings themselves: GTK's own
     * settings files, and the compositor's configuration.
     *
     * One writer, many reactors. No client ever writes a compositor config
     * or a gtk settings.ini; it writes a key, and this applies it.
     */
    public class Applier : Object {

        private Core.Config config;
        private Compositor.Backend backend;
        private uint gtk_source = 0;
        private uint compositor_source = 0;

        public Applier (Compositor.Backend backend) {
            this.config = Core.Config.get_default ();
            this.backend = backend;

            foreach (var key in new string[] {
                    "font-ui", "font-mono", "icon-theme",
                    "cursor-theme", "cursor-size", "colour-mode" }) {
                config.appearance.changed[key].connect (() => queue_gtk ());
            }

            foreach (var key in new string[] {
                    "window-placement", "titlebar-side",
                    "titlebar-buttons", "animation-duration" }) {
                config.compositor.changed[key].connect (() => queue_compositor ());
            }

            // labwc's theme follows the palette and accent, and its menus and
            // titles the interface font.
            foreach (var key in new string[] {
                    "colour-mode", "accent", "font-ui", "auto-sunrise", "auto-sunset" }) {
                config.appearance.changed[key].connect (() => {
                    queue_compositor ();
                    schedule_palette_switch ();
                });
            }
            schedule_palette_switch ();
        }

        private uint palette_source = 0;

        /**
         * Under 'auto' the palette changes with the time of day and no key
         * changes with it. GTK programs follow on their own (Ui.Theme keeps a
         * timer); labwc cannot, so its theme is re-selected here at the
         * boundary.
         */
        private void schedule_palette_switch () {
            if (palette_source != 0) {
                Source.remove (palette_source);
                palette_source = 0;
            }
            if (config.appearance.get_string ("colour-mode") != "auto") {
                return;
            }
            palette_source = Timeout.add_seconds (config.seconds_until_palette_change (), () => {
                palette_source = 0;
                write_gtk_settings ();
                apply_compositor.begin ();
                schedule_palette_switch ();
                return Source.REMOVE;
            });
        }

        /** Applies everything once at start-up, so a fresh account is correct. */
        public void apply_all () {
            write_gtk_settings ();
            apply_compositor.begin ();
        }

        // Writes are coalesced: dragging a cursor-size slider would otherwise
        // rewrite the file on every frame.
        private void queue_gtk () {
            if (gtk_source != 0) {
                Source.remove (gtk_source);
            }
            gtk_source = Timeout.add (200, () => {
                gtk_source = 0;
                write_gtk_settings ();
                return Source.REMOVE;
            });
        }

        private void queue_compositor () {
            if (compositor_source != 0) {
                Source.remove (compositor_source);
            }
            compositor_source = Timeout.add (200, () => {
                compositor_source = 0;
                apply_compositor.begin ();
                return Source.REMOVE;
            });
        }

        private async void apply_compositor () {
            try {
                yield backend.apply_configuration ();
            } catch (GLib.Error e) {
                Core.Log.warn ("cannot apply compositor configuration: %s", e.message);
            }
        }

        /**
         * GTK reads these files at start-up; there is no way to push font or
         * icon theme to an already-running GTK application from outside it
         * without the settings portal. Applications started after a change pick
         * it up, which is the same behaviour every other desktop has here.
         */
        private void write_gtk_settings () {
            var palette = config.resolved_palette ();
            var dark = (palette != "light");

            var font = config.appearance.get_string ("font-ui");
            var icons = config.appearance.get_string ("icon-theme");
            var cursor = config.appearance.get_string ("cursor-theme");
            var cursor_size = config.appearance.get_int ("cursor-size");
            var prefer_dark = dark ? 1 : 0;

            var body = new StringBuilder ();
            body.append ("# Generated by centaur-settingsd. Edits are overwritten.\n");
            body.append ("[Settings]\n");
            body.append (@"gtk-font-name=$font\n");
            body.append (@"gtk-icon-theme-name=$icons\n");
            body.append (@"gtk-cursor-theme-name=$cursor\n");
            body.append (@"gtk-cursor-theme-size=$cursor_size\n");
            body.append (@"gtk-application-prefer-dark-theme=$prefer_dark\n");

            // GTK3 applications are still a large part of any real session.
            foreach (var version in new string[] { "gtk-4.0", "gtk-3.0" }) {
                var dir = Path.build_filename (
                    Environment.get_user_config_dir (), version);
                var path = Path.build_filename (dir, "settings.ini");

                try {
                    if (!FileUtils.test (dir, FileTest.IS_DIR)) {
                        File.new_for_path (dir).make_directory_with_parents ();
                    }
                    FileUtils.set_contents (path, body.str);
                } catch (GLib.Error e) {
                    Core.Log.warn ("cannot write %s: %s", path, e.message);
                }
            }

            Core.Log.debug ("gtk settings written (palette=%s)", palette);
        }
    }
}
