centaur_base_center = executable('centaur-base-center',
  centaur_core_sources,
  centaur_compositor_sources,
  centaur_ui_sources,
  version_vala,
  files(
    'page.vala',
    'pages/overview.vala',
    'pages/appearance.vala',
    'pages/security.vala',
    'window.vala',
    'main.vala',
  ),
  dependencies: ui_deps,
  install: true,
  install_dir: bindir,
)
