centaur_topbar = executable('centaur-topbar',
  centaur_core_sources,
  centaur_compositor_sources,
  centaur_ui_sources,
  version_vala,
  files(
    'indicator.vala',
    'indicators/clock.vala',
    'indicators/battery.vala',
    'indicators/network.vala',
    'indicators/volume.vala',
    'indicators/power.vala',
    'indicators/launcher.vala',
    'indicators/workspaces.vala',
    'indicators/focused-window.vala',
    'bar.vala',
    'main.vala',
  ),
  dependencies: ui_deps + [layershell_dep],
  install: true,
  install_dir: bindir,
)
