gtk_wayland_dep = dependency('gtk4-wayland')

centaur_topbar = executable('centaur-topbar',
  centaur_core_sources,
  centaur_compositor_sources,
  centaur_ui_sources,
  version_vala,
  protocol_sources['wlr-foreign-toplevel-management-unstable-v1'],
  files(
    'toplevel-tracker.c',
    'toplevel-tracker.vapi',
    'toplevels.vala',
    'indicator.vala',
    'indicators/clock.vala',
    'indicators/battery.vala',
    'indicators/network.vala',
    'indicators/volume.vala',
    'indicators/power.vala',
    'indicators/launcher.vala',
    'indicators/workspaces.vala',
    'indicators/taskbar.vala',
    'indicators/focused-window.vala',
    'bar.vala',
    'main.vala',
  ),
  include_directories: include_directories('.'),
  dependencies: ui_deps + [layershell_dep, wayland_client_dep, gtk_wayland_dep],
  install: true,
  install_dir: bindir,
)
