#!/usr/bin/env python3
"""Generate Centaur DE's GTK4 stylesheets from design-system/tokens.json.

Two kinds of token, because GTK4 CSS treats them differently:

  colours  ->  emitted as @define-color, so centaur-settingsd can redefine the
               accent block at runtime and every module picks it up with a
               CssProvider reload.
  sizes    ->  GTK4 CSS has no variable mechanism for lengths, so spacing,
               radii and font sizes are substituted literally into the
               component rules at build time. That substitution is the reason
               this generator exists: it keeps one source of truth.

Usage:
    tools/generate.py --out ../app/data/themes
    tools/generate.py --out ../app/data/themes --preview preview.html
    tools/generate.py --check          # fail if generated output is stale
"""

from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from color import best_ink, mix  # noqa: E402

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
TOKENS = ROOT / "tokens.json"
TEMPLATE = ROOT / "templates" / "components.css.in"

BANNER = "/* Generated by design-system/tools/generate.py from tokens.json.\n   Do not edit. Edit tokens.json or templates/components.css.in. */\n"

PLACEHOLDER = re.compile(r"\{\{\s*([a-z0-9_.-]+)\s*\}\}", re.IGNORECASE)


def load() -> dict:
    with TOKENS.open() as fh:
        return json.load(fh)


def flatten(node, prefix=""):
    """{'surface': {'card': '#fff'}} -> {'surface.card': '#fff'}"""
    out = {}
    for key, value in node.items():
        path = f"{prefix}{key}"
        if isinstance(value, dict):
            out.update(flatten(value, f"{path}."))
        else:
            out[path] = value
    return out


def cssname(prefix: str, path: str) -> str:
    """'surface.card' -> 'centaur_surface_card' (GTK colour names allow no dots)."""
    return f"{prefix}_{path.replace('.', '_').replace('-', '_')}"


def resolve_accent(accent: dict, steps: dict) -> dict:
    """Map a palette's step choice onto one accent ramp.

    Ink is never taken on trust. Whatever the palette asks for, the generator
    picks whichever of white or the ramp's dark ink actually reads on the
    resolved fill -- otherwise light mode ships white-on-amber at 3.2:1.
    """
    base = accent[steps["base"]]
    return {
        "base": base,
        "bright": accent[steps["bright"]],
        "dim": accent[steps["dim"]],
        "ink": best_ink(base, "#ffffff", accent["ink"]),
    }


def palette_css(data: dict, palette_name: str) -> str:
    prefix = data["meta"]["prefix"]
    palette = data["palettes"][palette_name]
    colours = flatten({k: v for k, v in palette.items()
                       if k in ("surface", "border", "text", "control", "status")})

    lines = [BANNER, f"/* palette: {palette_name} */\n"]

    for path, value in colours.items():
        lines.append(f"@define-color {cssname(prefix, path)} {value};")

    # Tinted backgrounds for status chips, derived rather than hand-listed.
    alpha = palette["tint-alpha"]
    lines.append("")
    lines.append("/* status tints */")
    for status in ("success", "warning", "danger", "info"):
        src = cssname(prefix, f"status.{status}")
        lines.append(f"@define-color {src}_bg alpha(@{src}, {alpha});")
    lines.append(f"@define-color {prefix}_accent_bg alpha(@{prefix}_accent_base, {alpha});")

    # Every accent's resolved fill, so the Appearance page can show all eight
    # swatches at once. Only the selected one is centaur_accent_base.
    lines.append("")
    lines.append("/* accent swatches */")
    for accent_name, accent in data["accents"].items():
        resolved = resolve_accent(accent, palette["accent-steps"])
        lines.append(
            f"@define-color {prefix}_swatch_{accent_name} {resolved['base']};"
        )
    lines.append("")

    return "\n".join(lines) + "\n"


def accent_css(data: dict, palette_name: str, accent_name: str) -> str:
    """The block centaur-settingsd regenerates at runtime. Must load FIRST."""
    prefix = data["meta"]["prefix"]
    steps = data["palettes"][palette_name]["accent-steps"]
    resolved = resolve_accent(data["accents"][accent_name], steps)

    lines = [f"/* accent: {accent_name} on {palette_name} */"]
    for role, value in resolved.items():
        lines.append(f"@define-color {prefix}_accent_{role} {value};")
    return "\n".join(lines) + "\n"


def swatch_rules(data: dict, sizes: dict) -> str:
    """One rule per accent, generated so the list cannot drift from the ramps."""
    prefix = data["meta"]["prefix"]
    lines = [
        "",
        "/* --- accent swatches (generated per ramp) ------------------------------- */",
        "",
        ".centaur-accent-swatch {",
        f"  border-radius: {sizes['radius.sm']};",
        f"  border: {sizes['border-width.hairline']} solid @{prefix}_border_default;",
        "}",
        "",
    ]
    for accent_name in data["accents"]:
        lines.append(
            f".centaur-accent-swatch.accent-{accent_name} "
            f"{{ background-color: @{prefix}_swatch_{accent_name}; }}"
        )
    return "\n".join(lines) + "\n"


def components_css(data: dict) -> str:
    """Substitute size tokens into the component template."""
    sizes = flatten(data["scale"])
    missing = []

    def sub(match):
        key = match.group(1)
        if key not in sizes:
            missing.append(key)
            return match.group(0)
        return str(sizes[key])

    body = PLACEHOLDER.sub(sub, TEMPLATE.read_text())
    body += swatch_rules(data, sizes)

    if missing:
        raise SystemExit(
            "unknown token(s) in components.css.in: " + ", ".join(sorted(set(missing)))
        )

    return BANNER + body


def accent_map(data: dict) -> str:
    """Resolved accent values per palette, read by centaur-settingsd."""
    out = {}
    for palette_name, palette in data["palettes"].items():
        steps = palette["accent-steps"]
        out[palette_name] = {
            name: resolve_accent(accent, steps)
            for name, accent in data["accents"].items()
        }
    return json.dumps(
        {
            "prefix": data["meta"]["prefix"],
            "default_accent": next(
                n for n, a in data["accents"].items() if a.get("default")
            ),
            "labels": {n: a["label"] for n, a in data["accents"].items()},
            "resolved": out,
        },
        indent=2,
    ) + "\n"


def preview_html(data: dict) -> str:
    """A swatch sheet for reviewing the system without building the app."""
    prefix = data["meta"]["prefix"]
    parts = ["<!DOCTYPE html><html lang='en'><head><meta charset='utf-8'>",
             "<title>Centaur Tokens</title>",
             "<style>",
             "body{font:13px/1.5 Inter,system-ui,sans-serif;margin:0;padding:32px;",
             "background:#0b0f14;color:#e6edf3}",
             "h1{font-size:20px;margin:0 0 4px}h2{font-size:14px;margin:32px 0 12px;",
             "color:#a9b6c3;font-weight:600;text-transform:uppercase;letter-spacing:.06em}",
             "p.note{color:#6e7d8c;margin:0 0 8px}",
             ".grid{display:flex;flex-wrap:wrap;gap:8px}",
             ".sw{width:132px;border:1px solid #2a333e;border-radius:10px;overflow:hidden}",
             ".sw .chip{height:52px}.sw .lbl{padding:6px 8px;font-size:11px}",
             ".sw .hex{color:#6e7d8c;font-family:'JetBrains Mono',monospace;font-size:10px}",
             "</style></head><body>",
             "<h1>Centaur design tokens</h1>",
             f"<p class='note'>Generated from tokens.json v{data['meta']['version']}. "
             "Reference sheet only &mdash; GTK4 is the real target.</p>"]

    for palette_name, palette in data["palettes"].items():
        parts.append(f"<h2>palette &middot; {palette_name}</h2><div class='grid'>")
        for path, value in flatten({k: v for k, v in palette.items()
                                    if k in ("surface", "border", "text",
                                             "control", "status")}).items():
            parts.append(
                f"<div class='sw'><div class='chip' style='background:{value}'></div>"
                f"<div class='lbl'>{path}<br><span class='hex'>{value}</span></div></div>"
            )
        parts.append("</div>")

    parts.append("<h2>accents &middot; ramps</h2>")
    for name, accent in data["accents"].items():
        parts.append(f"<p class='note'>{accent['label']}"
                     f"{' (default)' if accent.get('default') else ''}</p><div class='grid'>")
        for step in ("300", "400", "500", "600", "700", "800", "ink"):
            parts.append(
                f"<div class='sw'><div class='chip' style='background:{accent[step]}'></div>"
                f"<div class='lbl'>{step}<br><span class='hex'>{accent[step]}</span></div></div>"
            )
        parts.append("</div>")

    parts.append("</body></html>")
    return "\n".join(parts)


def swaylock_config(data: dict) -> str:
    """The lock screen, in the dark palette.

    Dark whatever the desktop's mode: a lock screen is often seen in a dark
    room at wake, and a white flash there is the worst moment to have one.
    The accent is the default one; centaur-topbar overrides the four accent
    keys on the command line with the user's current accent, so this file
    does not have to be regenerated when the accent changes.
    """
    pal = data["palettes"]["dark"]
    accent = resolve_accent(
        next(a for a in data["accents"].values() if a.get("default")),
        pal["accent-steps"])

    def hexa(value: str) -> str:
        return value.lstrip("#").lower()

    surface, border, text, status = (
        pal["surface"], pal["border"], pal["text"], pal["status"])
    none = "00000000"
    family = data["scale"]["font"]["family-ui"].split(",")[0].strip().strip("'\"")

    rows = [
        ("color", hexa(surface["window"])),
        ("font", family),
        ("indicator-radius", "72"),
        ("indicator-thickness", "6"),
        ("indicator-idle-visible", None),
        ("show-failed-attempts", None),
        ("ignore-empty-password", None),
        ("", ""),
        ("inside-color", hexa(surface["card"])),
        ("inside-clear-color", hexa(surface["card"])),
        ("inside-ver-color", hexa(surface["card"])),
        ("inside-wrong-color", hexa(surface["card"])),
        ("inside-caps-lock-color", hexa(surface["card"])),
        ("", ""),
        ("ring-color", hexa(border["default"])),
        ("ring-clear-color", hexa(text["secondary"])),
        ("ring-ver-color", hexa(accent["base"])),
        ("ring-wrong-color", hexa(status["danger"])),
        ("ring-caps-lock-color", hexa(status["warning"])),
        ("", ""),
        ("key-hl-color", hexa(accent["base"])),
        ("caps-lock-key-hl-color", hexa(accent["base"])),
        ("bs-hl-color", hexa(status["danger"])),
        ("caps-lock-bs-hl-color", hexa(status["danger"])),
        ("", ""),
        ("text-color", hexa(text["primary"])),
        ("text-clear-color", hexa(text["secondary"])),
        ("text-ver-color", hexa(accent["base"])),
        ("text-wrong-color", hexa(status["danger"])),
        ("text-caps-lock-color", hexa(status["warning"])),
        ("", ""),
        ("layout-bg-color", hexa(surface["card"])),
        ("layout-border-color", hexa(border["default"])),
        ("layout-text-color", hexa(text["primary"])),
        ("", ""),
        ("line-color", none),
        ("line-clear-color", none),
        ("line-ver-color", none),
        ("line-wrong-color", none),
        ("line-caps-lock-color", none),
        ("separator-color", none),
    ]
    lines = [
        "# Generated by design-system/tools/generate.py from tokens.json.",
        "# Do not edit. A personal ~/.config/swaylock/config takes precedence.",
        "",
    ]
    for key, value in rows:
        if key == "":
            lines.append("")
        elif value is None:
            lines.append(key)
        else:
            lines.append(f"{key}={value}")
    return "\n".join(lines) + "\n"


# (palette, accent) pairs shipped as wallpapers; the first is the default.
WALLPAPERS = [("dark", "emerald"), ("dark", "blue"), ("dark", "purple"),
              ("dark", "amber"), ("light", "emerald"), ("light", "blue")]


def wallpaper_svg(data: dict, palette_name: str, accent_name: str) -> str:
    """A quiet gradient wallpaper in one palette and accent.

    1920x1080 intrinsic size: swaybg decodes an image once at that size and
    scales it per output, so a larger canvas only costs memory for a picture
    made of gradients that upscale cleanly anyway.
    """
    pal = data["palettes"][palette_name]
    accent = resolve_accent(data["accents"][accent_name], pal["accent-steps"])
    surface, text = pal["surface"], pal["text"]
    dark = palette_name != "light"
    glow = 0.26 if dark else 0.20
    rings = 0.045 if dark else 0.07

    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by design-system/tools/generate.py from tokens.json. Do not edit. -->
<svg xmlns="http://www.w3.org/2000/svg" width="1920" height="1080" viewBox="0 0 1920 1080">
  <defs>
    <linearGradient id="base" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="{surface['window']}"/>
      <stop offset="1" stop-color="{surface['card']}"/>
    </linearGradient>
    <radialGradient id="glow" cx="0.80" cy="0.16" r="0.72">
      <stop offset="0" stop-color="{accent['base']}" stop-opacity="{glow}"/>
      <stop offset="1" stop-color="{accent['base']}" stop-opacity="0"/>
    </radialGradient>
    <radialGradient id="ember" cx="0.08" cy="1.02" r="0.60">
      <stop offset="0" stop-color="{accent['dim']}" stop-opacity="{glow * 0.6:.3f}"/>
      <stop offset="1" stop-color="{accent['dim']}" stop-opacity="0"/>
    </radialGradient>
  </defs>
  <rect width="1920" height="1080" fill="url(#base)"/>
  <rect width="1920" height="1080" fill="url(#glow)"/>
  <rect width="1920" height="1080" fill="url(#ember)"/>
  <g fill="none" stroke="{text['primary']}" stroke-opacity="{rings}" stroke-width="2">
    <circle cx="1536" cy="172" r="360"/>
    <circle cx="1536" cy="172" r="560"/>
    <circle cx="1536" cy="172" r="780"/>
    <circle cx="1536" cy="172" r="1020"/>
  </g>
</svg>
"""


# How strongly the accent tints a highlighted menu item, over the menu surface.
MENU_HIGHLIGHT = 0.20


def labwc_themerc(data: dict, palette_name: str, accent_name: str) -> str:
    """labwc's theme, so its window titlebars, root and window menus and
    window switcher look like the rest of Centaur.

    labwc draws these itself; GTK's stylesheet never reaches them. Colours are
    solid wherever the design system blends, via mix(): labwc repaints menus
    per frame and an opaque colour is both cheaper and exact.
    """
    pal = data["palettes"][palette_name]
    accent = resolve_accent(data["accents"][accent_name], pal["accent-steps"])
    surface, border, text, status = pal["surface"], pal["border"], pal["text"], pal["status"]
    scale = data["scale"]
    dark = palette_name != "light"

    def px(token: str) -> str:
        return token.replace("px", "")

    highlight = mix(accent["base"], surface["overlay"], MENU_HIGHLIGHT)
    hover = mix(text["primary"], surface["sidebar"], 0.10)
    shadow_active = "#00000070" if dark else "#0f171f30"
    shadow_inactive = "#00000040" if dark else "#0f171f18"

    rows = [
        ("# general", None),
        ("border.width", "1"),
        ("window.titlebar.padding.width", px(scale["space"]["sm"])),
        ("window.titlebar.padding.height", px(scale["space"]["xs"])),
        ("", None),
        ("# window borders and titlebars, matching the GTK headerbar", None),
        ("window.active.border.color", border["default"]),
        ("window.inactive.border.color", border["subtle"]),
        ("window.active.indicator.toggled-keybind.color", status["danger"]),
        ("window.active.title.bg.color", surface["sidebar"]),
        ("window.inactive.title.bg.color", surface["window"]),
        ("window.*.title.bg", "Solid"),
        ("window.active.label.text.color", text["primary"]),
        ("window.inactive.label.text.color", text["muted"]),
        ("window.label.text.justify", "center"),
        ("", None),
        ("# titlebar buttons", None),
        ("window.button.width", "28"),
        ("window.button.height", "28"),
        ("window.button.spacing", px(scale["space"]["xs"])),
        ("window.button.hover.bg.color", hover),
        ("window.button.hover.bg.corner-radius", px(scale["radius"]["sm"])),
        ("window.active.button.unpressed.image.color", text["secondary"]),
        ("window.inactive.button.unpressed.image.color", text["muted"]),
        ("", None),
        ("# shadows", None),
        ("window.active.shadow.size", "40"),
        ("window.inactive.shadow.size", "24"),
        ("window.active.shadow.color", shadow_active),
        ("window.inactive.shadow.color", shadow_inactive),
        ("", None),
        ("# menus: the desktop (root) menu and each window's menu", None),
        ("menu.overlap.x", "0"),
        ("menu.overlap.y", "0"),
        ("menu.width.min", "200"),
        ("menu.width.max", "320"),
        ("menu.border.width", "1"),
        ("menu.border.color", border["default"]),
        ("menu.items.bg.color", surface["overlay"]),
        ("menu.items.text.color", text["primary"]),
        ("menu.items.active.bg.color", highlight),
        ("menu.items.active.text.color", text["primary"]),
        ("menu.items.padding.x", px(scale["space"]["lg"])),
        ("menu.items.padding.y", "7"),
        ("menu.separator.width", "1"),
        ("menu.separator.padding.width", px(scale["space"]["md"])),
        ("menu.separator.padding.height", px(scale["space"]["sm"])),
        ("menu.separator.color", border["subtle"]),
        ("menu.title.bg.color", surface["overlay"]),
        ("menu.title.text.color", text["muted"]),
        ("menu.title.text.justify", "Left"),
        ("", None),
        ("# window switcher (Alt+Tab) and other on-screen displays", None),
        ("osd.bg.color", surface["overlay"]),
        ("osd.border.color", border["default"]),
        ("osd.border.width", "1"),
        ("osd.label.text.color", text["primary"]),
        ("osd.window-switcher.style-classic.padding", px(scale["space"]["md"])),
        ("osd.window-switcher.style-classic.item.padding.x", px(scale["space"]["lg"])),
        ("osd.window-switcher.style-classic.item.padding.y", px(scale["space"]["sm"])),
        ("osd.window-switcher.style-classic.item.active.border.width", px(scale["border-width"]["thick"])),
        ("osd.window-switcher.style-classic.item.active.border.color", accent["base"]),
        ("osd.window-switcher.style-classic.item.active.bg.color", highlight),
        ("osd.window-switcher.style-thumbnail.item.active.border.width", px(scale["border-width"]["thick"])),
        ("osd.window-switcher.style-thumbnail.item.active.border.color", accent["base"]),
        ("osd.window-switcher.style-thumbnail.item.active.bg.color", highlight),
        ("osd.window-switcher.preview.border.width", px(scale["border-width"]["thick"])),
        ("osd.window-switcher.preview.border.color", accent["base"]),
        ("osd.workspace-switcher.boxes.border.width", px(scale["border-width"]["thick"])),
        ("", None),
        ("# window snapping overlays", None),
        ("snapping.overlay.region.bg.color", accent["base"] + "40"),
        ("snapping.overlay.edge.bg.color", accent["base"] + "40"),
        ("snapping.overlay.region.border.color", accent["base"]),
        ("snapping.overlay.edge.border.color", accent["base"]),
    ]

    lines = [
        "# Generated by design-system/tools/generate.py from tokens.json. Do not edit.",
        f"# Centaur, {accent_name} on {palette_name}. Selected by centaur-settingsd from",
        "# org.centaur.appearance; see labwc-theme(5) for the keys.",
        "",
    ]
    for key, value in rows:
        if key == "":
            lines.append("")
        elif value is None:
            lines.append(key)
        else:
            lines.append(f"{key}: {value}")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=pathlib.Path,
                    default=ROOT.parent / "app" / "data" / "themes")
    ap.add_argument("--preview", type=pathlib.Path,
                    help="also write an HTML swatch sheet here")
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if output would change")
    args = ap.parse_args()

    data = load()
    artifacts: dict[pathlib.Path, str] = {}

    for palette_name in data["palettes"]:
        artifacts[args.out / f"tokens-{palette_name}.css"] = palette_css(data, palette_name)
        for accent_name in data["accents"]:
            artifacts[args.out / "accents" / f"{accent_name}-{palette_name}.css"] = \
                accent_css(data, palette_name, accent_name)

    artifacts[args.out / "components.css"] = components_css(data)
    artifacts[args.out / "accent-map.json"] = accent_map(data)
    artifacts[args.out / "swaylock.conf"] = swaylock_config(data)
    for palette_name in data["palettes"]:
        for accent_name in data["accents"]:
            name = f"Centaur-{accent_name}-{palette_name}"
            artifacts[args.out.parent / "labwc-themes" / name / "labwc" / "themerc"] = \
                labwc_themerc(data, palette_name, accent_name)
    for palette_name, accent_name in WALLPAPERS:
        name = f"centaur-{accent_name}-{palette_name}.svg"
        artifacts[args.out.parent / "backgrounds" / name] = \
            wallpaper_svg(data, palette_name, accent_name)

    if args.check:
        stale = [p for p, body in artifacts.items()
                 if not p.exists() or p.read_text() != body]
        if stale:
            print("stale generated output:", file=sys.stderr)
            for path in stale:
                print(f"  {path}", file=sys.stderr)
            print("run design-system/tools/generate.py", file=sys.stderr)
            return 1
        print(f"up to date ({len(artifacts)} files)")
        return 0

    for path, body in artifacts.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(body)

    if args.preview:
        args.preview.parent.mkdir(parents=True, exist_ok=True)
        args.preview.write_text(preview_html(data))
        print(f"wrote {args.preview}")

    print(f"wrote {len(artifacts)} files to {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
