#!/usr/bin/env python3
"""Generate Centaur DE's GTK4 stylesheets from design-system/tokens.json.

Two kinds of token, because GTK4 CSS treats them differently:

  colours  ->  emitted as @define-color, so centaur-settingsd can redefine the
               accent block at runtime and every module picks it up with a
               CssProvider reload.
  sizes    ->  GTK4 CSS has no variable mechanism for lengths, so spacing,
               radii and font sizes are substituted literally into the
               component rules at build time. That substitution is the reason
               this generator exists: it keeps one source of truth.

Usage:
    tools/generate.py --out ../app/data/themes
    tools/generate.py --out ../app/data/themes --preview preview.html
    tools/generate.py --check          # fail if generated output is stale
"""

from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from color import best_ink  # noqa: E402

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
TOKENS = ROOT / "tokens.json"
TEMPLATE = ROOT / "templates" / "components.css.in"

BANNER = "/* Generated by design-system/tools/generate.py from tokens.json.\n   Do not edit. Edit tokens.json or templates/components.css.in. */\n"

PLACEHOLDER = re.compile(r"\{\{\s*([a-z0-9_.-]+)\s*\}\}", re.IGNORECASE)


def load() -> dict:
    with TOKENS.open() as fh:
        return json.load(fh)


def flatten(node, prefix=""):
    """{'surface': {'card': '#fff'}} -> {'surface.card': '#fff'}"""
    out = {}
    for key, value in node.items():
        path = f"{prefix}{key}"
        if isinstance(value, dict):
            out.update(flatten(value, f"{path}."))
        else:
            out[path] = value
    return out


def cssname(prefix: str, path: str) -> str:
    """'surface.card' -> 'centaur_surface_card' (GTK colour names allow no dots)."""
    return f"{prefix}_{path.replace('.', '_').replace('-', '_')}"


def resolve_accent(accent: dict, steps: dict) -> dict:
    """Map a palette's step choice onto one accent ramp.

    Ink is never taken on trust. Whatever the palette asks for, the generator
    picks whichever of white or the ramp's dark ink actually reads on the
    resolved fill -- otherwise light mode ships white-on-amber at 3.2:1.
    """
    base = accent[steps["base"]]
    return {
        "base": base,
        "bright": accent[steps["bright"]],
        "dim": accent[steps["dim"]],
        "ink": best_ink(base, "#ffffff", accent["ink"]),
    }


def palette_css(data: dict, palette_name: str) -> str:
    prefix = data["meta"]["prefix"]
    palette = data["palettes"][palette_name]
    colours = flatten({k: v for k, v in palette.items()
                       if k in ("surface", "border", "text", "control", "status")})

    lines = [BANNER, f"/* palette: {palette_name} */\n"]

    for path, value in colours.items():
        lines.append(f"@define-color {cssname(prefix, path)} {value};")

    # Tinted backgrounds for status chips, derived rather than hand-listed.
    alpha = palette["tint-alpha"]
    lines.append("")
    lines.append("/* status tints */")
    for status in ("success", "warning", "danger", "info"):
        src = cssname(prefix, f"status.{status}")
        lines.append(f"@define-color {src}_bg alpha(@{src}, {alpha});")
    lines.append(f"@define-color {prefix}_accent_bg alpha(@{prefix}_accent_base, {alpha});")

    # Every accent's resolved fill, so the Appearance page can show all eight
    # swatches at once. Only the selected one is centaur_accent_base.
    lines.append("")
    lines.append("/* accent swatches */")
    for accent_name, accent in data["accents"].items():
        resolved = resolve_accent(accent, palette["accent-steps"])
        lines.append(
            f"@define-color {prefix}_swatch_{accent_name} {resolved['base']};"
        )
    lines.append("")

    return "\n".join(lines) + "\n"


def accent_css(data: dict, palette_name: str, accent_name: str) -> str:
    """The block centaur-settingsd regenerates at runtime. Must load FIRST."""
    prefix = data["meta"]["prefix"]
    steps = data["palettes"][palette_name]["accent-steps"]
    resolved = resolve_accent(data["accents"][accent_name], steps)

    lines = [f"/* accent: {accent_name} on {palette_name} */"]
    for role, value in resolved.items():
        lines.append(f"@define-color {prefix}_accent_{role} {value};")
    return "\n".join(lines) + "\n"


def swatch_rules(data: dict, sizes: dict) -> str:
    """One rule per accent, generated so the list cannot drift from the ramps."""
    prefix = data["meta"]["prefix"]
    lines = [
        "",
        "/* --- accent swatches (generated per ramp) ------------------------------- */",
        "",
        ".centaur-accent-swatch {",
        f"  border-radius: {sizes['radius.sm']};",
        f"  border: {sizes['border-width.hairline']} solid @{prefix}_border_default;",
        "}",
        "",
    ]
    for accent_name in data["accents"]:
        lines.append(
            f".centaur-accent-swatch.accent-{accent_name} "
            f"{{ background-color: @{prefix}_swatch_{accent_name}; }}"
        )
    return "\n".join(lines) + "\n"


def components_css(data: dict) -> str:
    """Substitute size tokens into the component template."""
    sizes = flatten(data["scale"])
    missing = []

    def sub(match):
        key = match.group(1)
        if key not in sizes:
            missing.append(key)
            return match.group(0)
        return str(sizes[key])

    body = PLACEHOLDER.sub(sub, TEMPLATE.read_text())
    body += swatch_rules(data, sizes)

    if missing:
        raise SystemExit(
            "unknown token(s) in components.css.in: " + ", ".join(sorted(set(missing)))
        )

    return BANNER + body


def accent_map(data: dict) -> str:
    """Resolved accent values per palette, read by centaur-settingsd."""
    out = {}
    for palette_name, palette in data["palettes"].items():
        steps = palette["accent-steps"]
        out[palette_name] = {
            name: resolve_accent(accent, steps)
            for name, accent in data["accents"].items()
        }
    return json.dumps(
        {
            "prefix": data["meta"]["prefix"],
            "default_accent": next(
                n for n, a in data["accents"].items() if a.get("default")
            ),
            "labels": {n: a["label"] for n, a in data["accents"].items()},
            "resolved": out,
        },
        indent=2,
    ) + "\n"


def preview_html(data: dict) -> str:
    """A swatch sheet for reviewing the system without building the app."""
    prefix = data["meta"]["prefix"]
    parts = ["<!DOCTYPE html><html lang='en'><head><meta charset='utf-8'>",
             "<title>Centaur Tokens</title>",
             "<style>",
             "body{font:13px/1.5 Inter,system-ui,sans-serif;margin:0;padding:32px;",
             "background:#0b0f14;color:#e6edf3}",
             "h1{font-size:20px;margin:0 0 4px}h2{font-size:14px;margin:32px 0 12px;",
             "color:#a9b6c3;font-weight:600;text-transform:uppercase;letter-spacing:.06em}",
             "p.note{color:#6e7d8c;margin:0 0 8px}",
             ".grid{display:flex;flex-wrap:wrap;gap:8px}",
             ".sw{width:132px;border:1px solid #2a333e;border-radius:10px;overflow:hidden}",
             ".sw .chip{height:52px}.sw .lbl{padding:6px 8px;font-size:11px}",
             ".sw .hex{color:#6e7d8c;font-family:'JetBrains Mono',monospace;font-size:10px}",
             "</style></head><body>",
             "<h1>Centaur design tokens</h1>",
             f"<p class='note'>Generated from tokens.json v{data['meta']['version']}. "
             "Reference sheet only &mdash; GTK4 is the real target.</p>"]

    for palette_name, palette in data["palettes"].items():
        parts.append(f"<h2>palette &middot; {palette_name}</h2><div class='grid'>")
        for path, value in flatten({k: v for k, v in palette.items()
                                    if k in ("surface", "border", "text",
                                             "control", "status")}).items():
            parts.append(
                f"<div class='sw'><div class='chip' style='background:{value}'></div>"
                f"<div class='lbl'>{path}<br><span class='hex'>{value}</span></div></div>"
            )
        parts.append("</div>")

    parts.append("<h2>accents &middot; ramps</h2>")
    for name, accent in data["accents"].items():
        parts.append(f"<p class='note'>{accent['label']}"
                     f"{' (default)' if accent.get('default') else ''}</p><div class='grid'>")
        for step in ("300", "400", "500", "600", "700", "800", "ink"):
            parts.append(
                f"<div class='sw'><div class='chip' style='background:{accent[step]}'></div>"
                f"<div class='lbl'>{step}<br><span class='hex'>{accent[step]}</span></div></div>"
            )
        parts.append("</div>")

    parts.append("</body></html>")
    return "\n".join(parts)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=pathlib.Path,
                    default=ROOT.parent / "app" / "data" / "themes")
    ap.add_argument("--preview", type=pathlib.Path,
                    help="also write an HTML swatch sheet here")
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if output would change")
    args = ap.parse_args()

    data = load()
    artifacts: dict[pathlib.Path, str] = {}

    for palette_name in data["palettes"]:
        artifacts[args.out / f"tokens-{palette_name}.css"] = palette_css(data, palette_name)
        for accent_name in data["accents"]:
            artifacts[args.out / "accents" / f"{accent_name}-{palette_name}.css"] = \
                accent_css(data, palette_name, accent_name)

    artifacts[args.out / "components.css"] = components_css(data)
    artifacts[args.out / "accent-map.json"] = accent_map(data)

    if args.check:
        stale = [p for p, body in artifacts.items()
                 if not p.exists() or p.read_text() != body]
        if stale:
            print("stale generated output:", file=sys.stderr)
            for path in stale:
                print(f"  {path}", file=sys.stderr)
            print("run design-system/tools/generate.py", file=sys.stderr)
            return 1
        print(f"up to date ({len(artifacts)} files)")
        return 0

    for path, body in artifacts.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(body)

    if args.preview:
        args.preview.parent.mkdir(parents=True, exist_ok=True)
        args.preview.write_text(preview_html(data))
        print(f"wrote {args.preview}")

    print(f"wrote {len(artifacts)} files to {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
